### ISSUE TITLE
the application closes as soon as I launch it

### ISSUE THREAD

**Issue by Yas246** [Giacomix02/fanControl#1]
Hi, I have victus 15-fa0xxx and the app just close when i start it

**Comment by Giacomix02** [comment]
hi, can i have more infos? You used .msi or .exe setup? Windows version?

**Comment by Yas246** [comment]
hi.
i use the .exe setup. I'm on windows 11 22h2. when I launch the app it appears briefly then closes
 i just try the .msi setup and it does the same thing

**Comment by Giacomix02** [comment]
I have the same Windows setup, the previus version of application run? If not, have your system installed WebView2?

**Comment by Yas246** [comment]
i just try the previous version, it doesn't work either. i doesn't have WebView2, i will install it and try again

**Comment by Giacomix02** [comment]
Thx, let me know

**Comment by Yas246** [comment]
i just install WebView2 and the work well. Is there a way to stop the fans? mine whistle at low rpm and it bothers me when I'm in a quiet place ( while studying). Quiet mode seems to do nothing and I have already disabled fan always on in the bios.

**Comment by Giacomix02** [comment]
In the original hp software for fan control there isn't any option to disabile fans, i can improve It but i don't know if It will work. I also idk if slider mode work, because i cloned the code from other repository. I just created and UI for a simply use of powershell commands

**Comment by Giacomix02** [comment]
so, i mark it as resolved issue, if you want to suggest new features create a new issue
