### ISSUE TITLE
Useless slider

### ISSUE THREAD

**Issue by Jordintown** [Giacomix02/fanControl#4]
Hi, i have a Victus 16 but the default, eco, quiet, and so on bar isn't working, maybe i have to change some other setting or something? I'd like to help testing and/or debugging this problem

**Comment by Giacomix02** [comment]
Hi, thank you for this issue, I've talked about it with other user in [this](https://github.com/Giacomix02/fanControl/issues/3) issue. 

Shortly: is an error from the api that i use, so when i have time i'll change it to a slider were you can choose different fan speed, from 0 rpm to max speed.
The process is simple, i have to change a few lines in the rust code, but i have to study for a while the api and how to set the speed.

Api link: [here](https://github.com/Giacomix02/fanControl/tree/main/src-tauri/omen-hub-but-better)

Thank you for downloading my app, let me know!

**Comment by Jordintown** [comment]
alright thanks for your app!

**Comment by Giacomix02** [comment]
If you want to help me to change it:

[This is the link to Api with a README](https://github.com/Giacomix02/fanControl/tree/main/src-tauri/omen-hub-but-better)

[Link to the Rust code to change](https://github.com/Giacomix02/fanControl/blob/main/src-tauri/src/main.rs)

You have also to change the html and the js but is very simple
